// boards

export const GET_BOARDS = "GET_BOARDS";
export const GET_BOARDS_INIT = "GET_BOARDS_INIT";
export const GET_BOARDS_SUCCESS = "GET_BOARDS_SUCCESS";
export const GET_BOARDS_FAIL = "GET_BOARDS_FAIL";
export const CREATE_BOARD = "CREATE_BOARD";
export const CREATE_BOARD_SUCCESS = "CREATE_BOARD_SUCCESS";

// Lists

export const GET_LISTS = "GET_LISTS";
export const GET_LISTS_INIT = "GET_LISTS_INIT";
export const GET_LISTS_SUCCESS = "GET_LISTS_SUCCESS";
export const GET_LISTS_FAIL = "GET_LISTS_FAIL";
export const CREATE_LIST = "CREATE_LIST";
export const DELETE_LIST = "DELETE_LIST";

// Cards

export const GET_CARDS = "GET_CARDS";
export const GET_CARDS_INIT = "GET_CARDS_INIT";
export const GET_CARDS_SUCCESS = "GET_CARDS_SUCCESS";
export const GET_CARDS_FAIL = "GET_CARDS_FAIL";
export const CREATE_CARD = "CREATE_CARD";
export const DELETE_CARD = "DELETE_CARD";

// CheckLists

export const GET_CHECKLISTS = "GET_CHECKLISTS";
export const GET_CHECKLISTS_INIT = "GET_CHECKLISTS_INIT";
export const GET_CHECKLISTS_SUCCESS = "GET_CHECKLISTS_SUCCESS";
export const GET_CHECKLISTS_FAIL = "GET_CHECKLISTS_FAIL";
export const CREATE_CHECKLIST = "CREATE_CHECKLIST";
export const DELETE_CHECKLIST = "DELETE_CHECKLIST";

// CheckItems

export const GET_CHECKITEMS = "GET_CHECKITEMS";
export const GET_CHECKITEMS_INIT = "GET_CHECKITEMS_INIT";
export const GET_CHECKITEMS_SUCCESS = "GET_CHECKITEMS_SUCCESS";
export const GET_CHECKITEMS_FAIL = "GET_CHECKITEMS_FAIL";
export const CREATE_CHECKITEM = "CREATE_CHECKITEM";
export const DELETE_CHECKITEM = "DELETE_CHECKITEM";
export const UPDATE_CHECKITEM = "UPDATE_CHECKITEM";
